### ISSUE TITLE
Get Google Analytics Code

### ISSUE THREAD

**Issue by naher94** [naidurubini/empact.cc#3]

**Comment by naidurubini** [comment]
Hopefully I have everything you need here. let me know if not

Tracking ID: UA-114859748-1

Global Site Tag (gtag.js)

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-114859748-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114859748-1');
</script>

**Comment by naher94** [comment]
unfortunately not the right code, if you log in and go to admin panel (bottom left) > tracking info > tracking code > and the thing in the box

**Comment by naidurubini** [comment]
log into which platform? @naher94

**Comment by naher94** [comment]
google analytics

**Comment by naidurubini** [comment]
I'm here: https://www.google.com/analytics/#?modal_active=none. don't' see admin panel? is there another place I should be?

**Comment by naher94** [comment]
DONE
